### ISSUE TITLE
Unraid docker integration help?

### ISSUE THREAD

**Issue by rvs007** [rtorchia/DSC-AlarmServer#1]
I'm migrating from a Windows server over to an Unraid server.  On my Windows server I have AlarmServer running as a python 2.7 script.  I need to keep this running because the Homebridge plugin for Envisalink depends on having this Alarmserver running.  For SmartThings I've already switched over to the Edge driver. 

In Unraid, I can run Docker containers but I'm not too familiar with adding a container manually (all the Docker containers I've added so far is from the CA).  Can someone who's done this post the steps to adding this into Unraid?  Thanks in advanced.

**Comment by rtorchia** [comment]
I'm not familiar with unraid, but does it have a terminal that you can use to type in commands?
If so, then follow the install instructions and see if it works

**Comment by rvs007** [comment]
Thanks @rtorchia!  I was hoping I could integrate the container through the Unraid GUI instead of running it from the CLI, but I did get it installed per the install instructions.  So thank you!  It's up and running.
